### ISSUE TITLE
Статусы онлайн

### ISSUE THREAD

**Issue by Hoffasha** [uz0/chatter.io#12]
Захожу под пользователем
Открываю любого пользователя онлайн
Ожидание: будет статус онлайн или оффлайн
По факту все Not active

**Comment by efim1382** [comment]
@dcversus у нас же вроде больше нет сущности contact, откуда брать online?

**Comment by dcversus** [comment]
уточнила у бека

**Comment by dcversus** [comment]
добавляем друг друга в контакты

**Comment by Hoffasha** [comment]
@efim1382 опять сломалось все
