### ISSUE TITLE
Подготовить релиз

### ISSUE THREAD

**Issue by dcversus** [uz0/chatter.io#124]
- [x] составить список актуальных багов
- [ ] устранить баги (проконтролировать \ сообщить

**Comment by Hoffasha** [comment]
@dcversus @efim1382 
- [ ]  Опять картинка пропала (моб версия)
![4](https://user-images.githubusercontent.com/46968947/60851205-ce817f80-a1fa-11e9-97fb-ca33da3f7b06.png)
- [ ]  Не удаляется аватарка. В настройках профиля под аватаркой есть кнопка delete. После нажатия аватарка меняется на аватарку с буквой, но после выхода из настроек аватарка на месте
- [ ] Поиск по сообщениям, работает только по загруженным сообщениям. Если искомое слово находится где то далеко по истории чата, пока не будет нажата кнопка load more, поиск это слово не найдёт. Например слово Множественные
- [x] Очень нахватает возможности отправлять несколько картинок в одном сообщении - неактуально,  отправляются
- [x] нажимаю reply ввожу текст, перехожу в другой чат и отправляю сообщение, сообщение отправляется как reply, но в другой чат. win10 FF latest
- [x]  shift+enter не переносит строку
- [x] можно отправлять пустые сообщения
- [x]  Поле редактирования слишком маленькое, неудобно
- [x] Невозможно редактировать сообщение с картинкой, при попытке добавить текст сообщение невалидный url
- [x] Нужно сделать так, чтобы клик по @mention не перезагружал страницу, а сразу открывал чат с юзером. 
- [x] При редактировании сообщения с картинкой, ломается вёрстка (моб версия)
- [x] Не открывается меню сообщения, если сообщение содержит только картинку. Нельзя переслать и ответить (моб версия)
- [x] При открытии картинки из пересланного сообщения, открывается и картинка и меню сообщения
- [x] На форме смены пароля по ссылке из письма, неправильный текст (не понял, что не так)
