### ISSUE TITLE
Изучить новые макеты и оценить сложность правок

### ISSUE THREAD

**Issue by dcversus** [uz0/chatter.io#128]
- [ ] составить список фич что уже на макете встречаются
- [ ] расписать у этого списка сложность в системе - сложно, легко, не понимаю
записать список в комментарии к задаче

**Comment by efim1382** [comment]
- Таски
![image](https://user-images.githubusercontent.com/13278088/61057703-7f0ba100-a3fe-11e9-850c-c00c3d48e4d2.png)
Таски вроде не особо сложные, я так понимаю это просто перебор по массиву из сообщения? Но вместе с этим откуда таски берутся для попапа?
![image](https://user-images.githubusercontent.com/13278088/61057922-e6c1ec00-a3fe-11e9-8c38-af678d338c40.png)

- Модалка добавления таска
![image](https://user-images.githubusercontent.com/13278088/61057538-35bb5180-a3fe-11e9-940a-c976d55d7c13.png)
Модалка не сложная, тут все понятно

- Модалка добавления чата
![image](https://user-images.githubusercontent.com/13278088/61057456-099fd080-a3fe-11e9-9523-be1be6061fdc.png)
Это не сложно, но что с инпутом для сообщения? он всегда будет доступен при открытой модалке? типа я смогу сообщения отправять пока она открыта, но не буду видеть их в это время. И как оно должно выглядеть, когда открыта правая панель? Инпут в том случае сдвинут и будет на половину от модалки

- Spaces
![image](https://user-images.githubusercontent.com/13278088/61057875-ce51d180-a3fe-11e9-89e0-a23c9f0ead8e.png)
Тут ничего не понятно. Это блог какой то чтоль? И что за хэштэги, их если добавил в посте, то потом можно группировать по ним? 

---
И еще не особо понятно что открывается при клике сюда?
![image](https://user-images.githubusercontent.com/13278088/61059269-63ee6080-a401-11e9-8adb-5a297a0c2980.png)
