### ISSUE TITLE
Поиск по сообщениям глобальный

### ISSUE THREAD

**Issue by dcversus** [uz0/chatter.io#129]
Ищем текст в сообщении, если нету то делаем подгрузку + 1, если нету то делаем подгрузку + n пока не поймем что это первая подгрузка, в процесс крутим спинер

> Поиск по сообщениям, работает только по загруженным сообщениям. Если искомое слово находится где то далеко по истории чата, пока не будет нажата кнопка load more, поиск это слово не найдёт. Например слово Множественные

**Comment by dcversus** [comment]
Проблема: мы не можем искать на серве
Решение: асинхронно подгружаем все сообщения со всех подписок, по очередно подгружая вверх по истории, пока не найдем искомую фразу

В UI отражаем что мы ищем, добавляем кнопку stop search (и если юзер очистил строку поиска или как-то иначе ушел с результатов поиска также отбрасываем поиск корректно!)

В идеале подумать как можно хранить результаты поиска чтобы лучше оптимизировать работу с сетевыми запросами и подумать над тем как стоит визуализировать процесс (с учетом его длительности)

**Comment by Hoffasha** [comment]
Пока что не работает @efim1382

**Comment by efim1382** [comment]
> Пока что не работает @efim1382

@Hoffasha ага, он в пр-е https://github.com/uz0/chatter.io/pull/134 в ветке `global-search`. Ждет  ревью
