### ISSUE TITLE
Имя бандла генерируется из хеша

### ISSUE THREAD

**Issue by dcversus** [uz0/chatter.io#132]
юзаем https://www.npmjs.com/package/webpack-plugin-hash-output или аналог 

> с настоящего времени в требования к разработке добавляется независимость от кеша браузера (и соответственно CDN). Раньше я об этом не писал потому что полагал что в наше время это очевидно и входит автоматически.

**Comment by efim1382** [comment]
я залил. Оно и без плагина нормально работает 
![image](https://user-images.githubusercontent.com/13278088/61630048-50f44f80-ac8f-11e9-868a-397be9909628.png)
