### ISSUE TITLE
Сброс фильтра если отправляешь сообщение

### ISSUE THREAD

**Issue by dcversus** [uz0/chatter.io#141]
> Не сразу понял, что произошло. Нажал на #тег, отфильтровались сообщения, далее ввожу текст отправляю и ничего не происходит, полное ощущение, что сообщение не отправилось и что-то сломалось. Нужно нажать reset, для того, что бы снять филтр по тегу, и эта кнопка не очень то заметная.

предлагаю сбрасывать фильтр, когда юзер отправил сообщение

**Comment by Hoffasha** [comment]
Отправлю сюда, чтобы не забыть/не потерять
после отправки сообщения фильтр сбрасывается, но открывается боковая панель с информацией о пользователе, нотисы и т д, вопрос, должно так быть, или она не должна повторно открываться?
