### ISSUE TITLE
Пересылка сообщений (forward) не работает

### ISSUE THREAD

**Issue by Hoffasha** [uz0/chatter.io#147]
При пересылке сообщения кому либо, просто передвигает чат вверх на неопределенное количество строк и ничего не пересылает, сбоку же видно Forwarde.. и в чате выглядит как пустое место. Сообщение от Hoffa с текстом "345"
![image](https://user-images.githubusercontent.com/46968947/61879673-31ae2a00-aefc-11e9-8fbe-82fa42da7dff.png)

**Comment by efim1382** [comment]
Дублирует #143
