### ISSUE TITLE
Загрузка файлов

### ISSUE THREAD

**Issue by Hoffasha** [uz0/chatter.io#159]
Очень долго загружается 200Мб файл. Больше 10 мин.

**Comment by danilstoyanov** [comment]
Пытался пофиксить, посоветовался с Лисой, проблема может быть не стороне бэкенда. Нужен дальнейший ресёрч по данному issue.

**Comment by dcversus** [comment]
https://kb.universablockchain.com/p/102#large-attachment 

так как загрузка файлов очень медленная поэтому добавлена загрузка файла асинхронно по кусочкам. В кратце: добавлены поля async и chunk_id и увеличен размер кусочка до 1 Мб. Вам теперь не нужно ждать ответа об отправке каждого кусочка, а отправлять всё подряд
