### ISSUE TITLE
Смена пароля

### ISSUE THREAD

**Issue by Hoffasha** [uz0/chatter.io#162]
ошибка при смене пароля по ссылке из письма. 1. Перехожу в форму восстановления пароля. 2. Указываю email. 3. Перехожу по ссылке из письма. 4. Указываю новый пароль и его подтверждение. Получаю нотификацию Error (без дополнительного текста). 5. Перехожу на форму входа, ввожу почту и новый пароль. - все ок.

**Comment by danilstoyanov** [comment]
@Hoffasha можно тестить
