### ISSUE TITLE
Некорректная отправка спейса в реальном времени

### ISSUE THREAD

**Issue by Hoffasha** [uz0/chatter.io#166]
после f5 сообщение появится
![image](https://user-images.githubusercontent.com/46968947/63310787-b8400680-c304-11e9-9107-170b83c2689c.png)

**Comment by efim1382** [comment]
@Hoffasha ну я вот сейчас перепроверил, все норм

**Comment by Hoffasha** [comment]
"

**Comment by Hoffasha** [comment]
@efim1382 актуально, завтра покажу

**Comment by efim1382** [comment]
Поправил
