### ISSUE TITLE
Некорректная отправка картинок/гифок

### ISSUE THREAD

**Issue by Hoffasha** [uz0/chatter.io#169]
Отправить просто картинку/гифку нельзя, текст обязателен : ошибка Info No data to send
второй попыткой гифка отправилась, но выглядела как пустое сообщение около 15 сек, потом появилась, с картинкой также, но быстрее загрузилась

**Comment by efim1382** [comment]
Это потому что не было прогресбара на файлах при загрузке. Ты отправлял сообщение, когда картинка еще не загрузилась. Залил
