### ISSUE TITLE
Удаление контактов

### ISSUE THREAD

**Issue by efim1382** [uz0/chatter.io#176]
В апи есть метод для удаления контакта, надо бы уже реализовать
https://kb.universablockchain.com/unichat_api/102#deleting-contact

**Comment by dcversus** [comment]
В правую панель, по аналогии с leave chat добавляем "удалить контакт"

**Comment by efim1382** [comment]
Я залил все под удаление, но есть баг. На первое удаление приходит успех, но контакт продолжает оставаться у меня (и после перезагрузки). На 2+ удаления приходит `undefined method 'destroy' for nil:NilClass`
