### ISSUE TITLE
Компании

### ISSUE THREAD

**Issue by dcversus** [uz0/chatter.io#183]
- [ ]  Создание компании
- [ ]   Экран компании (все подписки фильтруются по org_id и меняется заголовок на название компании)
- [ ]   Настройки компании (отдельная страница, похожа на new dialog с тремя разделами, на одной странице, след за другом)
- [ ]   Настройки, раздел general, внутри него - изменить название организации, изменить логотип и удалить организацию (по аналогии настройками пользователя)
- [ ]   Настройки, раздел users, пригласить пользователя, список юзеров где можно изменить их "роли" админ или участник, а также выгнать пользователя (все по аналогии с похожей панелью в свойствах группового чата)
- [ ]   Настройки, раздел conversations - список всех подписок организации, с централизованной возможностью удалить групповой чат из org_id, а также ссылка "создать новый диалог", который открывает стандартное окно создание новой переписки
- [ ]   Уведомления о новых сообщениях внутри компании
- [ ] ВНИМАНИЕ!! ЕСЛИ Я СОЗДАЮ СООБЩЕНИЕ \ ДИАЛОГ ВНУТРИ ОРГАНИЗАЦИИ НЕ ЗАБЫВАЕМ ЕМУ ПРИПИСЫВАТЬ org_id!!

**Comment by efim1382** [comment]
update company
- logo
- color
- name
- members

new company
- logo
- color
- name
- members

delete company

**Comment by dcversus** [comment]
- [ ] Создание компании
- [ ] Экран компании (все подписки фильтруются по org_id и меняется заголовок на название компании)
- [ ] Настройки компании (отдельная страница, похожа на new dialog с тремя разделами, на одной странице, след за другом)
- [ ] Настройки, раздел general, внутри него - изменить название организации, изменить логотип и удалить организацию (по аналогии настройками пользователя)
- [ ] Настройки, раздел users, пригласить пользователя, список юзеров где можно изменить их "роли" админ или участник, а также выгнать пользователя (все по аналогии с похожей панелью в свойствах группового чата)
- [ ] Настройки, раздел conversations - список всех подписок организации, с централизованной возможностью удалить групповой чат из org_id, а также ссылка "создать новый диалог", который открывает стандартное окно создание новой переписки
- [ ] Уведомления о новых сообщениях внутри компании

ВНИМАНИЕ!! ЕСЛИ Я СОЗДАЮ СООБЩЕНИЕ \ ДИАЛОГ ВНУТРИ ОРГАНИЗАЦИИ НЕ ЗАБЫВАЕМ ЕМУ ПРИПИСЫВАТЬ org_id!!

**Comment by dcversus** [comment]
![image](https://user-images.githubusercontent.com/8696354/64428957-a0ff6800-d0bd-11e9-84ea-1ebec114ab49.png)

1) вместо названия unichat в компании название компании
2) вместо "всего списка подписок" тот же список, только отфильтрованный по org_id
3) появляется иконка "настройки компании" которая ведет на настройки

**Comment by dcversus** [comment]
не забудь forward внутри компании

**Comment by dcversus** [comment]
фича про фиды, также не забыть что пересылка идет в фиды в рамках компании
