### ISSUE TITLE
Баг с redux 

### ISSUE THREAD

**Issue by efim1382** [uz0/chatter.io#3]
https://github.com/uz0/chatter.io/blob/master/src/components/messages_container/index.js#L107
Вот тут при выводе в консоль this.props и nextProps - id сообщений в чате (chatIds) одинаковые и в this.props  и в nextProps.

Так я не могу отследить состояние "не было сообщения - появилось сообщение"

Я переписывал редьюсеры сообщений, вроде как я не изменяю напрямую state, я копирую его
https://github.com/uz0/chatter.io/blob/master/src/store/messages/reducers.js#L17

Я делал console.log(state) перед внесением изменений в условный stateChatIds, который скопирован с оригинального state, и делал console.log(state) после изменений. state я напрямую не изменял, но в обоих console.log(state) данные одинаковые

Еще вот тут компонент не обновлялся, пока я не добавил в connect весь родительский объект
https://github.com/uz0/chatter.io/blob/master/src/components/subscription-item/message/index.js#L81

**Comment by dcversus** [comment]
я не поняла вообще в чем трабла, кейс "небыло сообщения - появилось сообщение", у тебя reducer обновляет messages_list только, а это обьект... обновление обьектов connect не может отследить, храни дополнительно еще одно поле, которое будет простым текстовым ключом и когда у тебя будут приходит новые сообщения, то обновляй этот ключ.

Это например может быть id последнего сообщения или еще что-то, не важно.
