### ISSUE TITLE
Бесконечная загрузка

### ISSUE THREAD

**Issue by Hoffasha** [uz0/chatter.io#41]
MainWindow > New chat
Если в поле поиска указать недопустимый символ, начинает бесконечно крутиться прогресс бар. например “пробел кавычка”

**Comment by Hoffasha** [comment]
@efim1382 актуально
![image](https://user-images.githubusercontent.com/46968947/55882426-32b98680-5bad-11e9-8ffb-9b726d8391b8.png)

**Comment by efim1382** [comment]
@Hoffasha поправил, но оно еще не применилось
