### ISSUE TITLE
Ранжирование

### ISSUE THREAD

**Issue by Hoffasha** [uz0/chatter.io#42]
MainWindow → New chat 
Странное ранжирование поисковой выдачи, выдает по алфавиту
я ввожу test-  и первым у меня появляется ник, в котором "test-" находится в конце ника, а  ищу я все начинающиеся с test-

**Comment by efim1382** [comment]
@dcversus ну я проверял все вхождения фразы, делать поиск по тем, которые начинаются с введенной фразы?

**Comment by efim1382** [comment]
Поиск по "начинается с"

**Comment by Hoffasha** [comment]
@efim1382  не помогло(
![image](https://user-images.githubusercontent.com/46968947/55882313-fd149d80-5bac-11e9-836a-44f55bdac66f.png)

**Comment by efim1382** [comment]
@Hoffasha @dcversus ну это отдает так бэкенд
