### ISSUE TITLE
Название прикрепленных файлов 

### ISSUE THREAD

**Issue by Hoffasha** [uz0/chatter.io#43]
MainWindows → Chat 1-1
Прикрепляем файл к сообщению и отправляем.  Отображается  слово File и MIME Type, а хотелось бы название.
![image](https://user-images.githubusercontent.com/46968947/54353895-3b7a7380-4666-11e9-8fcc-fc92b5ce3ee3.png)

**Comment by efim1382** [comment]
надо бы наверное от бэкенда получать названия
