### ISSUE TITLE
Загрузка файлов

### ISSUE THREAD

**Issue by Hoffasha** [uz0/chatter.io#44]
MainWindows → Chat 1-1
Загружаем текстовый файл блокнота пустой (в блокноте с инфой все норм), и вместо загрузки появляется красный значок, как при оффлайн сообщениях, он не пересылается и после обновления страницы все пропадает
Вывод - пустой блокнотный файл не грузит
![image](https://user-images.githubusercontent.com/46968947/54353937-5d73f600-4666-11e9-9a9c-6d266e3e7f17.png)

**Comment by efim1382** [comment]
![image](https://user-images.githubusercontent.com/13278088/55144608-e3ee0480-5149-11e9-88eb-cec4ca72e370.png)

от бэкенда приходит ошибка при отправке пустого файла

**Comment by dcversus** [comment]
!на клиенте не позволяем отправлять пустые файлы, окей?
