### ISSUE TITLE
подгрузка архива сообщений

### ISSUE THREAD

**Issue by dcversus** [uz0/chatter.io#48]
- [ ] когда доходишь до самого старого загруженного сообщения загружать еще
- [ ] использовать решение, в котором контейнер будет рендерить ТОЛЬКО то что находится в зоне видимости (контейнер с виртуальным скроллом)  (virtual scroll)

**Comment by efim1382** [comment]
@Hoffasha второй пункт я не делал, с ним пока сложности. Подгрузка есть

**Comment by Hoffasha** [comment]
@efim1382 первый пункт тоже не работает, загрузка идет бесконечная
