### ISSUE TITLE
Айфоны, сафари моб версия пуш/звук уведомления

### ISSUE THREAD

**Issue by Hoffasha** [uz0/chatter.io#80]
Нет звуковых и пуш уведомлений.
На андроиде только звуковые.

**Comment by efim1382** [comment]
https://stackoverflow.com/questions/50433873/reactjs-fcm-not-working-in-safari-browser

![image](https://user-images.githubusercontent.com/13278088/57681640-c2cd6e80-7638-11e9-8e69-831c637a9ec6.png)
