### ISSUE TITLE
Узкое окно и панель свойства

### ISSUE THREAD

**Issue by Hoffasha** [uz0/chatter.io#99]
Когда на десктопе окно узкое, то самая правая панель - свойства - не убирается и перекрывает чат. Нужно сделать, чтобы она убиралась
![image](https://user-images.githubusercontent.com/46968947/57857672-4c776a80-77f8-11e9-9a22-dde6a335e07a.png)

**Comment by dcversus** [comment]
гуд поинт не показывать правую панель если экран меньше определенной ширины =(
